# Generated by Django 5.2.6 on 2025-09-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_type',
            field=models.CharField(choices=[('NEWS', 'Новости'), ('ARTICLES', 'Статья')], max_length=8),
        ),
        migrations.CreateModel(
            name='UserSubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subs', through='main_page.UserSubs', to='main_page.category'),
        ),
    ]
